# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener_v1
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

      # MySQL Database
  db:
    image: mysql:8.0
    container_name: shorter_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}  # This matches DB_DATABASE in .env
      MYSQL_USER: ${DB_USERNAME}      # This matches DB_USERNAME in .env
      MYSQL_PASSWORD: ${DB_PASSWORD}  # This matches DB_PASSWORD in .env
    volumes:
      - db_data:/var/lib/mysql
      - ./indesign.sql:/docker-entrypoint-initdb.d/url_shortner.sql  # Import initial data
    ports:
      - "3306:3306"  # Expose MySQL to connect from host

       # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_v1
    environment:
      PMA_HOST: db  # Connects to the MySQL container by its service name
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Must match the root password in the db service
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8080
    depends_on:
      - db

volumes:
  db_data:
