# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: shortener_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: url_shortner
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/url_shortner.sql

volumes:
  db_data:
